### PR TITLE
Soback 135 custom logo

### PR DESCRIPTION
**Pull request by jorntx**
Clickable logo in new top menu bar.

### CODE REVIEW

**Review by thomasegense — CHANGES_REQUESTED** [review]
Putting the logo in top and taking up space and taking space from the application/results is not optimal. I had expected it to be in the top  left corner (and much bigger size).

@jesperlauridsen What to hear your opinion about this.

**Comment by jorntx** [comment]
> Putting the logo in top and taking up space and taking space from the application/results is not optimal. I had expected it to be in the top left corner (and much bigger size).
> Link should open in new tab.
> 
> @jesperlauridsen What to hear your opinion about this.

That was my first shot at it (check git log) but it was very in your face and looked very unbalanced on the page.

After consulting with @jesperlauridsen we came up with this.

@thomasegense try to check out and see for yourself https://github.com/netarchivesuite/solrwayback/pull/154/commits/b644d3ca2a57dfd3722cdb61f0a10e96c3d3502e

**Comment by jorntx** [comment]
@thomasegense and @jesperlauridsen please look again...:)

**Review by thomasegense — APPROVED** [review]
OK

**Review by thomasegense — APPROVED** [review]
Accepted, no more fiddling with logo for now.

**Pull request merged**
