### PR TITLE
Export speedup

### LINKED ISSUE #329: Improve export speed
The current experimental fields-exporter in solrWayback issues standard `cursorMark` requests against the underlying Solr.

Assume we have 100 Solr nodes and page 1000 documents at a time (a reasonable approximation of the index at the Royal Danish Library which has 143 nodes).

In a classic Solr Cloud setup each cursorMark request for 1000 documents will cause processing at each Solr node, where each node will return 1000 document-IDs and sort values, but only 10 will be used on average (1000 documents / 100 nodes = 10 documents/node). This means there is a lot of wasted processing for each request. A local test gave an export with high variance in speed, from 12-130 records/second and high load across the Solr Cloud.

If the Solr nodes were queried sequentially, each cursorMark request would involve only a single Solr node and all 1000 documents returned would be used. This was tested against the setup at [Netarkivet](https://www.kb.dk/find-materiale/samlinger/netarkivet) and the export speed here was ~1200 documents/second with load localized to a single Solr node. It would be quite feasible to query 1/4 of all nodes on parallel, which would increase export speed to ~30,000 documents/second in our not-so-hypothetical setup.

There is clearly much to gain by rewiring the SolrWayback export code. Two possibilities comes to mind:

## External shard requests
Introduce an endpoint listing the shards in the Solr setup and add a `shardID` parameter to the export endpoint.

* Pro: Very easy to implement in SolrWayback
* Con: Puts the burden of merging (and grouping if that is required) the result on the caller

## Internal shard requests
Add parallel explicit shard requests to the existing code, taking care to support grouping. Basically a mimic of [Solr streaming](https://solr.apache.org/guide/8_8/streaming-expressions.html) with the crucial difference that export of stored fields is possible.

* Pro: Makes field export performant without any extra work for the end user
* Con: Not trivial to implement, needs consideration of Solr Cloud topology

### PR DESCRIPTION
**Pull request by tokee**
Major refactor of SolrWayback export. See the blogpost [Beware the cursorMark, my son!](https://sbdevel.wordpress.com/2023/10/24/beware-the-cursormark-my-son/) for overall principle.

The primary purpose of this pull request is to lower overall processing needs and increase performance when exporting from a multi-shard Solr setup. Single shard (aka Standalone) setups will see no change in speed. The easiest way to experiment with the alleged performance improvement is through the "unit test" `ShardStreamingTest.testStageSpeed` by ignoring the method name and pointing it to the production index :smiley: Do take care to not run it while a regular export is underway.

Tweaks to the improved export is done in `solrwayback.properties`. The sample setup in the `test`-folder holds the 4 properties, together with comments explaining what they do.

This closes #329 

Rewriting the export code gave a few secondary improvements:

* Core export code is now much cleaner, located in the `solr.SolrStream*` classes
* Throughput speed is logged during export every 10 seconds, instead of logging by fixed count
* Export `maxresults` limit is now checked at the last part of the export chain, making the limit reliable both with regard to deduplication and resource expansion

Note: Export speedup was implemented by Toke Eskildsen as an outside collaborator, **not** as part of his job at the Royal Danish Library.

### CODE REVIEW

**Review by thomasegense — CHANGES_REQUESTED** [review]
Very solid work. JDK code quality one some classes like  CollectionUtils.
Not easy to understand code, but ease of usage is what is important, and framework is hidding it away.
I did a few very trivial fixes, so pull first.

**1:**
Is it correct that the export-stream does not set facet + highlight to false?
By luck facet=false iby default in edixmax definition, but I would be pleased if this was
made explicit by the code. But highlight is default 'on', so here it is important to turn it off. (even more speedup!!!)


**2:**
 Too excessive log.info when streaming?
Try run unittest and see output. This class in particular:
 StreamingSolrWarcExportBufferedInputStream
Can some be turned into debug?
And why is it logged double ? (same millis)

`11:49:30.189 [main] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream - Warcs read:270 arcs read:0
11:49:30.189 [main] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream - loadMore(): No more documents available after 270 docs read
11:49:30.189 [main] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream - warcExport buffer empty
11:49:30.189 [main] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream - Warcs read:270 arcs read:0
`
I will update the CHANGES.md :)

There is a few spin-offs from  this PR. But I want this PR merged fast due to 5.0 release and they most be solved later.
I will accept PR when the facet+highlight is fixed.

New issues herel isted here by my priority:
https://github.com/netarchivesuite/solrwayback/issues/443
https://github.com/netarchivesuite/solrwayback/issues/440
https://github.com/netarchivesuite/solrwayback/issues/442

**Comment by tokee** [comment]
Your changes are causing a 100% diff and for the properties it seems that you are adding "windows linebreaks" (`CRLF`) instead of just `LF`!? It can be seen in GitHubs commit view.

**Comment by thomasegense** [comment]
I hate eclipse more and more. Using it from my Windows computer decided to do this.
You welcome to overwrite it totally.

**Comment by tokee** [comment]
Regarding facet+group+highlight: They are disabled in `SRequest.getMergedSolrQuery`. But thanks for the sanity check.
I have reduced logging somewhat. Feel free to reduce further.

I have no idea about the double logging and right now I don't have time for a deep dive into that. Sorry.

**Comment by thomasegense** [comment]
And merged

**Pull request merged**
