### PR TITLE
Upgraded HttpSolrClient to Http2SolrClient

### LINKED ISSUE #443: Upgrade deprecated HttpSolrClient
HttpSolrClient is used for all calls with SolrJ.
After solr dependencies has been upgraded, switch to new solr client.

 */
@Deprecated(since = "9.0")
public class HttpSolrClient extends BaseHttpSolrClient 

It may be a good idea if this could be solved first,so another rewrite will not be required.

Upgrade all dependencies to solr 9.4.0:
https://github.com/netarchivesuite/solrwayback/issues/440

### PR DESCRIPTION
**Pull request by VictorHarbo**
Switching to the recommended Http2SolrClient and removing some un used imports found along the way. 

Closes #443

### CODE REVIEW

**Comment by thomasegense** [comment]
It works with Solr8 and Solr9 that supports HTTP2.
But unfortunately it does not work with Solr7 that can use  HTTP1.
Besides us (Denmark)) Hungary also a solr7 in production with a very large index.
So I suggest we postpone this upgrade as long as possible or until we have upgraded to Solr9 in Denmark. (which is 50 CPU/years of indexing)




Gives this error when talking to Solr7.
`caused by: java.io.IOException: frame_size_error/invalid_frame_length
        at org.eclipse.jetty.http2.HTTP2Session.toFailure(HTTP2Session.java:566)
        at org.eclipse.jetty.http2.HTTP2Session.access$2700(HTTP2Session.java:80)
        at org.eclipse.jetty.http2.HTTP2Session$StreamsState.onSessionFailure(HTTP2Session.java:1857)
        at org.eclipse.jetty.http2.HTTP2Session$StreamsState.access$400(HTTP2Session.java:1436)
        at org.eclipse.jetty.http2.HTTP2Session.onSessionFailure(HTTP2Session.java:511)
        at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:506)
        at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onConnectionFailure(Parser.java:414)
        at org.eclipse.jetty.http2.HTTP2Connection$ParserListener.onConnectionFailure(HTTP2Connection.java:397)
        at org.eclipse.jetty.http2.parser.BodyParser.notifyConnectionFailure(BodyParser.java:223)
        at org.eclipse.jetty.http2.parser.BodyParser.connectionFailure(BodyParser.java:215)
        at org.eclipse.jetty.http2.parser.Parser.connectionFailure(Parser.java:209)
        at org.eclipse.jetty.http2.parser.Parser.parseHeader(Parser.java:155)
        at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:121)
`

**Comment by VictorHarbo** [comment]
Yes, lets wait. seems like SolrJ 9.6 is going to introduce a nem client, which might be useful in this case.

**Comment by VictorHarbo** [comment]
This is ready for another review. Currently deployed at the test machine

**Review by thomasegense — APPROVED** [review]
Nothing broken it seems.

**Pull request merged**
