### PR TITLE
More streaming cleanup

### PR DESCRIPTION
**Pull request by tokee**
This pull request introduces a generic mechanism for the problem "Given a (large) list of queries, return all matches while performing deduplication".

This pull request uses the new mechanism to simplify some of the methods in `NetarchiveSolrClient`.

Note: Refactoring did funny things to `Twitter2HTML.java`. Better check that Twitter playback works as intended!

### CODE REVIEW

**Review by thomasegense — CHANGES_REQUESTED** [review]
Thanks for the refactoring. 
But all playback is broken, probably a simple mistake somewhere. Just search and find an HTML page and try playback.

`022-10-17 08:12:34 [http-nio-8080-exec-30] DEBUG dk.kb.netarchivesuite.solrwayback.parsers.HtmlParserUrlRewriter(HtmlParserUrlRewriter.java:165) - #unique urlset to resolve for arc-url 'https://www.pvda
.nl/?ll' :100
2022-10-17 08:12:34 [http-nio-8080-exec-30] ERROR dk.kb.netarchivesuite.solrwayback.service.SolrWaybackResource(SolrWaybackResource.java:1018) - ServiceException(HTTP 500) in Service:
java.lang.NullPointerException: null
        at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
        at dk.kb.netarchivesuite.solrwayback.solr.NetarchiveSolrClient.mergeInto(NetarchiveSolrClient.java:724)
        at dk.kb.netarchivesuite.solrwayback.solr.NetarchiveSolrClient.lambda$findNearestDocuments$2(NetarchiveSolrClient.java:714)
`

**Comment by tokee** [comment]
Thanks for the review. I'll look at the concrete problem. I have put the issue on hold as I have learned more about streaming processing, so the rewrite has not finished.

**Comment by tokee** [comment]
I did a fair amount of rewriting nd have more in store, but this looks stable from my point of view. I have not performed any integration tests!

**Comment by thomasegense** [comment]
Fear not! I shall test. (today or tomorrow)

**Comment by tokee** [comment]
Please note commit [0f81d24](https://github.com/netarchivesuite/solrwayback/pull/269/commits/0f81d24f0f9a7df952f7f068ec830f1e807618d4) which implements streaming image export, but does not expose it as a service.

**Comment by thomasegense** [comment]
@tokee  Warc export gives an empty files(also no WARC metadata header)
 CSV export works.
Here is  the tomcat log. 
`2022-10-21 14:59:08 [http-nio-8080-exec-13] DEBUG dk.kb.netarchivesuite.solrwayback.service.SolrWaybackResource(SolrWaybackResource.java:326) - Export warc. gzip=false query:id:"20220707111526/eZ 8b46mIHeytPImfxzJKw==" filterquery:[]
2022-10-21 14:59:08 [http-nio-8080-exec-13] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream(StreamingSolrWarcExportBufferedInputStream.java:144) - loadMore(): No more documents available after 0 docs read
2022-10-21 14:59:08 [http-nio-8080-exec-13] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream(StreamingSolrWarcExportBufferedInputStream.java:90) - warcExport buffer empty
2022-10-21 14:59:08 [http-nio-8080-exec-13] INFO  dk.kb.netarchivesuite.solrwayback.export.StreamingSolrWarcExportBufferedInputStream(StreamingSolrWarcExportBufferedInputStream.java:91) - Warcs read:0 arcs read:0
`

**Comment by tokee** [comment]
Alright, seems like the `TestExportWarcStreaming` unit tests aren't too telling :-)

I'll convert this to a draft and do the integration test themselves so that I am sure to deliver a more solid pull request and not just a "The unit tests passes"-one.

**Comment by thomasegense** [comment]
Good weekend Toke. Enjoy :)

**Comment by tokee** [comment]
@thomasegense your logged query is `id:"20220707111526/eZ 8b46mIHeytPImfxzJKw=="` and if I'm not mistaken there is a `+` instead of a space in the real ID for the document. I was able to reproduce your case on `streaming2`, but also on `master`! It looks like another case of problems with encoding/decoding parameters where the `+` in read as a space when doing exporting.

Exporting with queries **not** having `+` in them works fine for me. Both on `streaming2` and `master`.

**Pull request merged**
