### PR TITLE
Harvest resource page first stab

### PR DESCRIPTION
**Pull request by jorntx**
First try on harvest resource page. It is activated from the toolbar (5'th broken image tag from the right :)) ) and may need som tampering with your solrwayback.properties to get the web page preview to work. Just ping me if the preview doesn't work.

Remember to redeploy to Tomcat and restart it before testing.

@thomasegense you can suffice with testing the functionality in Tomcat

### CODE REVIEW

**Comment by jorntx** [comment]
Hold your horses on this one @jesperlauridsen  - @thomasegense found some issues I would like to fix before your review

**Comment by jorntx** [comment]
Finally approved by Egense and now good to go for your code review @jesperlauridsen

**Comment by jesperlauridsen** [comment]
2 minor errors:

also-weird-stuff
weird-stuff

**Comment by jorntx** [comment]
1. Webpage preview broken image icon behaviour is our fallback if the webpage preview times out or in your case is not setup correctly. You can click the link and go to the resource. As stated in my intro remarks in the PR you need to tamper with your Solr settings to get it to work - we can set it up together later.

2. The hover behaviour is weird and probably due to my pseudo table layout not really working out with the hover mechanism. You have already pointed me to a pseudo table you have made that might work better - I will look into that 👍 

The massive white space is due to the resource both lacking 'preview' and 'missing resources'. I will see if I can fix that and I also see that the 'no missing resources' message doesn't show up in the right side as it should.

**Comment by jorntx** [comment]
I have given it a touch up now:

1. Removed the hover action that was responsible for the weird behaviour shown above
2. Delt with some of the white space when no preview is available
3. Added more clear information when preview image fails to load
 - try to give it a spin again.

**Review by jesperlauridsen — COMMENTED** [review]
Looks very good.

**Review by jesperlauridsen — APPROVED** [review]
:+1:

**Review by thomasegense — APPROVED** [review]

**Pull request merged**
