### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by anjackson**
This is an proposal to support deployment using Docker. Currently, it only allows a few aspects of SolrWayback to be easily configured via environment variables, but otherwise works well.  As well as a `Dockerfile`, there is also a `docker-compose.yml` file which can be used to build a run the image locally, along with a `ukwa/webarchive-discovery-solr` instance of Solr that gets populated with some test data.

Before I go any further with this approach, I just wanted to check if you were interested in supporting Docker deployments?

### CODE REVIEW

**Comment by thomasegense** [comment]
I started the container and got and the search page was working: http://localhost:8080/solrwayback/
So that was nice and easy.
But searching was not working, looks like the solr-server was not found. 

I am not a docker expert sorry. Can you tell me the commands to build and run it after a fresh checkout?
And do I have to change any properties? I would be best if it just worked. 

Because I can not find the tomcat log-file, I am quite helpless in finding the error.

Can you write a docker paragraph in the project README.md with instructions? 
I will accept the PR when I get it working :)

**Comment by anjackson** [comment]
Sure! I'll continue working on it - I should probably have put a bit more documentation in first - sorry!

**Comment by anjackson** [comment]
I added some info on using the Docker Compose file, which might help, but you'll probably also hit another issue concerning Solr configuration....

With other tools, my approach so far has been to make sure the client sets any Solr parameters that _that_ client requires, e.g. `defType=edismax`, `pf=text` and `qf=text` are [in code](https://github.com/ukwa/ukwa-ui/blob/39d1f334b8d2699cb22a24cfa18189bea70a9ac4/src/main/java/com/marsspiders/ukwa/solr/SolrSearchService.java#L204-L257).  The SolrWayback approach is to put these kinds of options [in solr config](https://github.com/netarchivesuite/solrwayback/blob/a2e3c1bb616e1e41ae9571af41ab0544768cc645/src/test/resources/solr/netarchivebuilder/conf/solrconfig.xml#L820-L877) - i.e. the client expects the `solrconfig` has particular settings in place, as well as having the expected schema.

Currently, the outcome of this difference is that when you run SolrWayback against the UKWA Solr service, the search won't work unless you supply the field name. i.e. a search for `this` does nothing, but a search for `title:this` will work.

How would you feel about specifying search options from the client? Perhaps as some kind of generic configuration option like `default.solr.opts.X = Y` e.g. `default.solr.opts.defType=edismax` etc.? Or is this a bad idea, e.g. is it better to make Solr always behave the same way for all clients?

**Comment by thomasegense** [comment]
I will talk to Toke about the solr-config.

But I can still not get the container running.
first command was OK: 'docker-compose build'
Running the second command gave this error and the tomcat exited:
docker-compose up




54    0     0   3848      0 --:--:-- --:--:-- --:--:--  3848
populate_1     | <html>
populate_1     | <head>
populate_1     | <meta http-equiv="Content-Type"
content="text/html;charset=utf-8"/>
populate_1     | <title>Error 404 Not Found</title>
populate_1     | </head>
populate_1     | <body><h2>HTTP ERROR 404</h2>
populate_1     | <p>Problem accessing /solr/discovery`/update. Reason:
populate_1     | <pre>    Not Found</pre></p>
populate_1     | </body>
populate_1     | </html>
solr_1         | 2022-03-01 09:28:06.264 INFO  (qtp1282788025-18) [   ]
o.a.s.s.SolrDispatchFilter Could not consume full client request
solr_1         | java.io.IOException: Committed before 100 Continues
solr_1         | at
org.eclipse.jetty.server.HttpChannelOverHttp.continue100(HttpChannelOverHttp.java:210)
solr_1         | at
org.eclipse.jetty.server.Request.getInputStream(Request.java:830)
solr_1         | at
org.apache.solr.servlet.SolrDispatchFilter.consumeInputFully(SolrDispatchFilter.java:387)
solr_1         | at
org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:378)
solr_1         | at
org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
solr_1         | at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
solr_1         | at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
solr_1         | at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
solr_1         | at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
solr_1         | at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
solr_1         | at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
solr_1         | at
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
solr_1         | at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
solr_1         | at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
solr_1         | at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
solr_1         | at
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
solr_1         | at
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
solr_1         | at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
solr_1         | at
org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
solr_1         | at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
solr_1         | at org.eclipse.jetty.server.Server.handle(Server.java:534)
solr_1         | at
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
solr_1         | at
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
solr_1         | at
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
solr_1         | at
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
solr_1         | at
org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
solr_1         | at
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
solr_1         | at
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
solr_1         | at
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
solr_1         | at
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
solr_1         | at
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
solr_1         | at java.lang.Thread.run(Thread.java:750)
solrwayback_populate_1 exited with code 0

**Comment by anjackson** [comment]
Sorry, rather silly error there. Should work now.

**Comment by thomasegense** [comment]
Hi Andy.  Exit code was 0 now when running 'docker-compose up'. 
And it seemed to push 1 record into solr.

But how do I start the container? 
So I can access:
http://localhost:8080/solrwayback
(and http://localhost:8983/solr)

**Comment by anjackson** [comment]
The `solr_populate_1` service is supposed to exit, after having send data to Solr.  After running `docker-compose up` you should see logs from all three services, and the search should work (with the caveats mentioned above).  The Solr service itself should be on port 18983, i.e. http://localhost:18983/solr/ (I used 18983 instead of 8983 to avoid clashing with any existing Solr service.

**Comment by thomasegense** [comment]
The solr is running on 18983.
But where is the tomcat?
localhost:8080/solrwayback/  (not working)

**Comment by anjackson** [comment]
Ah, sorry, I'd chopped and changed this a bit and got confused.  It's on 8085, but I've updated it to run on 18080 to be more consistent.

**Comment by thomasegense** [comment]
Almost there!
I can access solrwayback on http://localhost:8085/solrwayback/
and search is worker.
But clicking a result will open: http://localhost:8080/solrwayback/    (this comes from solrwayback.properties: wayback.baseurl)
So the two property-files needs to match this these ports.

**Comment by anjackson** [comment]
That should get us a bit closer. There are other things that should be configurable, and there's no chromium in there yet. Also, there's various bits and bobs I need to do to make it actually work with our systems, like fetching WARC records over HTTP.

**Comment by anjackson** [comment]
I think that should do screenshots now. However, as we don't store WARCs on a plain filesystem I have no way to test this at present.

**Comment by thomasegense** [comment]
The properties seems to correct now. But without the warc-files, there is little working besides showing the search results, which are also missing the image.
An example of playback URL is:
http://localhost:18080/solrwayback/services/viewForward?source_file_path=BL-20180608080940689-00643-63~ukwa-h3-pulse-annual~8443.warc.gz&offset=467639088

Notice the path to the warc-file. But without indexing properly from a folder, we it would be hard to make it work.

I will accept the PR and write some additional text about these limitations.

**Pull request merged**
